[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "clinical-quality-ecqm-cql-engine"
version = "2.0.0"
description = "eCQM-Engine: Clinical Quality Language (CQL) & CMS Quality Measure Engine"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
clinical-quality-ecqm-cql-engine = "ecqm_cql_engine.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/clinical-quality-ecqm-cql-engine"
Repository = "https://github.com/abusuraihsakhri/clinical-quality-ecqm-cql-engine.git"
